complete alphabetical_grouping and search friend
PavelMarkevich/VkMessenger pull request #10
Opened 2020-02-14 08:15 UTC by PavelMarkevich

2020-02-17 07:57 UTC, AliaksandrHabrusevich requested changes

2020-02-17 07:57 UTC, AliaksandrHabrusevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendViewModel.swift
> +    var usersNames: [String]
почему String а не UserModel?

2020-02-17 07:57 UTC, AliaksandrHabrusevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendViewModel.swift
> +    var group = [Group]()
naming. Сам подумай что не так

2020-02-17 07:57 UTC, AliaksandrHabrusevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendViewModel.swift
> +    var filterGroup = [Group]()
naming. Сам подумай что не так

2020-02-17 07:57 UTC, AliaksandrHabrusevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendViewModel.swift
> +    func countOfSector() -> Int {
что такое сектор?

2020-02-17 07:57 UTC, AliaksandrHabrusevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendViewModel.swift
> +    func fillingTableView(indexPath: IndexPath) -> String? {
где TableView? кто и чем ее заполняет?

2020-02-17 07:57 UTC, AliaksandrHabrusevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendsViewController.swift
> +                self?.viewModel.grouping(users: model)
этот вызов должен быть внутри вью модели

2020-02-24 07:30 UTC, PavelMarkevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendViewModel.swift
> +    var usersNames: [String]
Я использовал структуру для группировки по алфавиту. Больше она ни для чего не нужна. Поэтому string

2020-02-24 07:31 UTC, PavelMarkevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendViewModel.swift
> +    var group = [Group]()
переименовал

2020-02-24 07:31 UTC, PavelMarkevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendViewModel.swift
> +    var filterGroup = [Group]()
переименовал

2020-02-24 07:32 UTC, PavelMarkevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendViewModel.swift
> +    func countOfSector() -> Int {
неправильно подписал. Изменил на Section

2020-02-24 07:34 UTC, PavelMarkevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendsViewController.swift
> +                self?.viewModel.grouping(users: model)
создал новый метод : getUserMode в котором я получаю модель и вызываю метод grouping

2020-02-24 07:34 UTC, PavelMarkevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendViewModel.swift
> +    func fillingTableView(indexPath: IndexPath) -> String? {
добавил tableView и в этом методе заполняю таблицу

2020-02-25 09:13 UTC, PavelMarkevich commented on VKMessenger/VKMessenger/Screens/Friends/FriendViewModel.swift
> +    var usersNames: [String]
исправил

2020-02-27 13:19 UTC, AliaksandrHabrusevich approved these changes

2020-02-27 13:45 UTC, merged